data = read.table('my_data.txt')
head(data)

sumS = 0

model = lm(y ~ x1, data = data, x = T, y = T)
print(model)
plot(data$x1, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[1] = sum(squaredError)

model = lm(y ~ x2, data = data, x = T, y = T)
print(model)
plot(data$x2, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x2')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[2] = sum(squaredError)

model = lm(y ~ x3, data = data, x = T, y = T)
print(model)
plot(data$x3, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x3')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[3] = sum(squaredError)

model = lm(y ~ x4, data = data, x = T, y = T)
print(model)
plot(data$x4, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x4')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[4] = sum(squaredError)

model = lm(y ~ x5, data = data, x = T, y = T)
print(model)
plot(data$x5, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x5')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[5] = sum(squaredError)

model = lm(y ~ x6, data = data, x = T, y = T)
print(model)
plot(data$x6, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x6')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[6] = sum(squaredError)

model = lm(y ~ x7, data = data, x = T, y = T)
print(model)
plot(data$x7, data$y)
abline(model, col = 'red')
predicted = predict(model, data)
plot(predicted, xlab = 'y as x7')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[7] = sum(squaredError)

model = lm(y ~ x1 + x2, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[8] = sum(squaredError)

model = lm(y ~ x1 + x2 + x3, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2 x3')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[9] = sum(squaredError)

model = lm(y ~ x1 + x2 + x3 + x4, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2 x3 x4')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[10] = sum(squaredError)

model = lm(y ~ x1 + x2 + x3 + x4 + x5, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2 x3 x4 x5')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[11] = sum(squaredError)

model = lm(y ~ x1 + x2 + x3 + x4 + x5 + x6, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2 x3 x4 x5 x6')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[12] = sum(squaredError)

model = lm(y ~ x1 + x2 + x3 + x4 + x5 + x7, data = data, x = T, y = T)
print(model)
predicted = predict(model, data)
plot(predicted, xlab = 'y as x1 x2 x3 x4 x5 x6 x7')
points(data$y, col = 'red', pch = 15)
error = abs(predicted - data$y)
plot(error)
squaredError = error * error
points(squaredError, col = 'red', pch = 16)
sumS[13] = sum(squaredError)

plot(sumS, type = 'l')
